SOFLAGS = -fPIC
LDSOFLAGS = -shared
LDDLFLAGS = -shared
CC = gcc
LD = gcc
CFLAGS = -g -O2 -Wall  -DHAVE_DISCID -DHAVE_CONFIG  -std=gnu11 -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security -Wold-style-definition -Wno-pointer-sign -Werror-implicit-function-declaration -Wno-unused-parameter -Wno-missing-field-initializers -MMD -MP -MF .dep-$(subst /,-,$@) -DREALTIME_SCHEDULING
LDFLAGS =  
HOSTCC = gcc
HOSTLD = gcc
HOST_CFLAGS = -g -O2 -Wall
HOST_LDFLAGS = 
COMPAT_LIBS = 
DL_CFLAGS = 
DL_LIBS = -ldl -Wl,--export-dynamic
PTHREAD_CFLAGS = -D_REENTRANT
PTHREAD_LIBS = -lpthread
PKG_CONFIG = /usr/bin/pkg-config
NCURSES_CFLAGS = -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  
NCURSES_LIBS = -lncursesw 
ICONV_CFLAGS = 
ICONV_LIBS = 
CDDB_CFLAGS = 
CDDB_LIBS = -lcddb 
CDIO_CFLAGS = 
CDIO_LIBS = -lcdio_cdda -lcdio -lm 
FLAC_CFLAGS = 
FLAC_LIBS = -lFLAC 
MAD_CFLAGS = 
MAD_LIBS = -lmad 
MODPLUG_CFLAGS = 
MODPLUG_LIBS = -lmodplug 
MPC_CFLAGS = 
MPC_LIBS = -lmpcdec -lm
VORBIS_CFLAGS = 
VORBIS_LIBS = -lvorbisfile 
LIBSYSTEMD_CFLAGS = 
LIBSYSTEMD_LIBS = -lsystemd 
WAVPACK_CFLAGS = 
WAVPACK_LIBS = -lwavpack 
AAC_CFLAGS = 
AAC_LIBS = -lfaad -lm
FFMPEG_CFLAGS = 
FFMPEG_LIBS = -lavformat -lavcodec 
PULSE_CFLAGS = -D_REENTRANT 
PULSE_LIBS = -lpulse -pthread 
ALSA_CFLAGS = 
ALSA_LIBS = -lasound 
JACK_CFLAGS = 
JACK_LIBS = -ljack 
SAMPLERATE_CFLAGS = 
SAMPLERATE_LIBS = -lsamplerate 
AO_CFLAGS = 
AO_LIBS = -lao 
OSS_CFLAGS = 
OSS_LIBS = 
DISCID_CFLAGS = 
DISCID_LIBS = -ldiscid 
bindir = /usr/local/bin
datadir = /usr/local/share
libdir = /usr/local/lib
mandir = /usr/local/share/man
exampledir = /usr/local/share/doc/cmus/examples
CONFIG_AAC = y
CONFIG_ALSA = y
CONFIG_AO = y
CONFIG_ARTS = n
CONFIG_CDIO = y
CONFIG_COREAUDIO = n
CONFIG_CUE = y
CONFIG_FFMPEG = y
CONFIG_FLAC = y
CONFIG_JACK = y
CONFIG_MAD = y
CONFIG_MIKMOD = n
CONFIG_MODPLUG = y
CONFIG_MP4 = n
CONFIG_MPC = y
CONFIG_MPRIS = y
CONFIG_OPUS = n
CONFIG_OSS = y
CONFIG_PULSE = y
CONFIG_ROAR = n
CONFIG_SAMPLERATE = y
CONFIG_SNDIO = n
CONFIG_SUN = n
CONFIG_VORBIS = y
CONFIG_VTX = n
CONFIG_WAV = y
CONFIG_WAVEOUT = n
CONFIG_WAVPACK = y
CONFIG_BASS = n
GINSTALL = install
topdir = /data/source/cmus
